Class {
	#name : #BMMenuConstants,
	#superclass : #Object,
	#category : #'Bruce-Mindmap-constants'
}

{ #category : #adding }
BMMenuConstants class >> addChild [
	^'Add Child' 
]

{ #category : #adding }
BMMenuConstants class >> addIcon [ 
	^'Add Icon'
]

{ #category : #adding }
BMMenuConstants class >> addImage [
	^'Add Image'
]

{ #category : #adding }
BMMenuConstants class >> addSibling [ 
	^'Add Sibling'
]

{ #category : #adding }
BMMenuConstants class >> backgroundColor [
	^'Background Color'
]

{ #category : #adding }
BMMenuConstants class >> color [
	^'Color'
]

{ #category : #adding }
BMMenuConstants class >> copyNode [
	^'Copy'
]

{ #category : #adding }
BMMenuConstants class >> cut [ 
	^'Cut'
]

{ #category : #adding }
BMMenuConstants class >> delete [
	^'Delete'
]

{ #category : #adding }
BMMenuConstants class >> details [
	^'Details'
]

{ #category : #adding }
BMMenuConstants class >> edit [
	^'Edit'
]

{ #category : #adding }
BMMenuConstants class >> font [
	^'Font' 
]

{ #category : #accessing }
BMMenuConstants class >> link [
	^'Link' 
]

{ #category : #adding }
BMMenuConstants class >> open [
	^'Open'
]

{ #category : #adding }
BMMenuConstants class >> paste [
	^'Paste'
]

{ #category : #adding }
BMMenuConstants class >> removeIcon [ 
	^'Remove Icon'
]

{ #category : #adding }
BMMenuConstants class >> removeImage [
	^'Remove Image'
]

{ #category : #adding }
BMMenuConstants class >> save [
	^'Save'
]
