Class {
	#name : #BMXMLTags,
	#superclass : #Object,
	#category : #'Bruce-Mindmap-constants'
}

{ #category : #constants }
BMXMLTags class >> background [
	^'background' 

]

{ #category : #constants }
BMXMLTags class >> childNode [
	^'node'

]

{ #category : #constants }
BMXMLTags class >> color [
	^'color'

]

{ #category : #constants }
BMXMLTags class >> font [
	^'font' 

]

{ #category : #constants }
BMXMLTags class >> foreground [
	^'foreground'

]

{ #category : #constants }
BMXMLTags class >> mindmap [
	^'mindmap'

]

{ #category : #constants }
BMXMLTags class >> rootNode [
	^'maintopic'

]

{ #category : #constants }
BMXMLTags class >> text [
	^'text'

]
