Class {
	#name : #BMXMLTags,
	#superclass : #Object,
	#category : #'Bruce-Mindmap-constants'
}

{ #category : #constants }
BMXMLTags class >> alpha [
	^'alpha'
]

{ #category : #constants }
BMXMLTags class >> background [
	^'background' 

]

{ #category : #constants }
BMXMLTags class >> blue [
	^'blue'
]

{ #category : #constants }
BMXMLTags class >> childNode [
	^'node'

]

{ #category : #constants }
BMXMLTags class >> color [
	^'color'

]

{ #category : #constants }
BMXMLTags class >> detail [
	^'detail'

]

{ #category : #constants }
BMXMLTags class >> familyName [
	^'familyName'
]

{ #category : #constants }
BMXMLTags class >> font [
	^'font' 

]

{ #category : #constants }
BMXMLTags class >> foreground [
	^'foreground'

]

{ #category : #constants }
BMXMLTags class >> green [
	^'green'
]

{ #category : #constants }
BMXMLTags class >> icon [
	^'icon'
]

{ #category : #constants }
BMXMLTags class >> iconAttribute [
	^name
]

{ #category : #accessing }
BMXMLTags class >> image [
	^'image'
]

{ #category : #accessing }
BMXMLTags class >> line [
	^'line'
]

{ #category : #accessing }
BMXMLTags class >> link [
	^'link' 
]

{ #category : #constants }
BMXMLTags class >> mindmap [
	^'mindmap'

]

{ #category : #constants }
BMXMLTags class >> pointSize [ 
	^'pointSize'
]

{ #category : #constants }
BMXMLTags class >> purpose [
	^'purpose'

]

{ #category : #constants }
BMXMLTags class >> red [
	^'red'
]

{ #category : #constants }
BMXMLTags class >> rootNode [
	^'maintopic'

]

{ #category : #constants }
BMXMLTags class >> slantValue [ 
	^'slantValue'
]

{ #category : #constants }
BMXMLTags class >> stretchValue [
	^'stretchValue'
]

{ #category : #accessing }
BMXMLTags class >> task [
	^'task'
]

{ #category : #constants }
BMXMLTags class >> text [
	^'text'

]

{ #category : #constants }
BMXMLTags class >> weightValue [
	^'weightValue'
]
